research_task:
  description: >
    Research successful crowdfunding campaigns similar to the user's project.
    
    Project Details:
    - Project Type: {project_type}
    - Target Amount: {target_amount}
    - Target Audience: {target_audience}
    
    Analyze the PDF to find:
    1. Similar successful campaigns
    2. Best practices for this type of project
    3. Target audience behavior patterns
    4. Optimal funding goals and reward structures
  expected_output: >
    A comprehensive research report including:
    - Success patterns for similar campaigns
    - Target audience insights
    - Recommended funding structures
    - Key success factors
  agent: market_researcher

strategy_task:
  description: >
    Develop a strategic campaign plan based on the research findings.
    
    Consider:
    - Project Type: {project_type}
    - Target Amount: {target_amount}
    - Target Audience: {target_audience}
    - Desired Tone: {tone}
    
    Create a strategy that maximizes campaign success potential.
  expected_output: >
    A detailed strategy including:
    - Campaign positioning
    - Reward tier structure
    - Marketing approach
    - Timeline recommendations
    - Key messaging points
  agent: campaign_strategist

content_task:
  description: >
    Create the crowdfunding campaign content using the research and strategy.
    
    Project Details:
    - Project: {project_type}
    - Goal: {target_amount}
    - Audience: {target_audience}
    - Tone: {tone}
    
    Write compelling content that will resonate with the target audience
    and drive contributions.
  expected_output: >
    A complete campaign post including:
    - Attention-grabbing headline
    - Compelling project story
    - Clear benefits and features
    - Reward tiers description
    - Strong call to action
    Formatted in markdown without code blocks
  agent: content_creator
